language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install openjdk-8-jdk
    - sudo update-java-alternatives -s java-1.8.0-openjdk-amd6
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install pyspark "dask[complete]"
    - pip install codecov
install:
    - pip install -r requirements.txt # install package + test dependencies
script: python -m pytest  # run tests
after_success:
    - codecov # submit coverage