language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install codecov
install:
    - pip install -r requirements.txt # install package + test dependencies
script: python -m pytest  # run tests
after_success:
    - codecov # submit coverage